### ISSUE TITLE
Not getting any stock data

### ISSUE THREAD

**Issue by wuerzelchen** [kwokwilliam/MTMR-TradingBar#5]
I tried to install based on the README.md.
The bar shows up, but the stock data is missing and in the console it shows constantly: **FAILURE: {}**
https://github.com/kwokwilliam/MTMR-TradingBar/blob/29bd71eecc99314a69b25fd9b96b646094a05722/touchbarserver/src/context/ticker.ts#L36

I pulled everything from the master branch.

**Comment by kwokwilliam** [comment]
I haven't been using this project actively nor maintaining it since I started a full time job. My guess would be that the yahoo finance API changed their format. 

I want to revisit this project one day but at this moment I don't have bandwidth for it.
